services:
  db:
    image: mysql:8.0 
    restart: always
    container_name: "portfoliodb"
    environment:
      - MYSQL_ROOT_PASSWORD=ro0tPassw0rd
    env_file:
      - ./config/.env.data
    ports:
      - ${MYSQL_PORT:-3308}:3306
    command: --log-bin-trust-function-creators=1
    volumes:
      - db_data:/var/lib/mysql
      - ./config/scripts/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./config/scripts/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql
      - ./config/conf.d/db.cnf:/etc/mysql/conf.d/db.cnf:ro

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "--password=ro0tPassw0rd",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  # stack pour le container d'api
  app:
    container_name: app-portfolio
    env_file:
      - ./config/.env.backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - ${PORT:-8079}:8079
    volumes:
      - ./medias:/code/medias
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /code/app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/.pytest_cache"
        - action: rebuild
          path: ./backend/requirements.txt

  # container pour l'authentification
  auth:
    container_name: auth-portfolio
    env_file:
      - ./config/.env.auth
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./auth/app/
          target: /code/app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/.pytest_cache"
        - action: rebuild
          path: ./auth/requirements.txt

  front-portfolio:
    container_name: front-portfolio
    image: nginx:alpine
    ports:
      - "8073:80"
    restart: always
    volumes:
      - ./frontend/:/usr/share/nginx/html/
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /usr/share/nginx/html/

  medias:
    container_name: medias
    image: nginx:alpine
    ports:
      - "8071:80"
    volumes:
      - ./medias/:/usr/share/nginx/html/medias
    restart: always

volumes:
  db_data:
