services:
  db:
    image: mysql:8.0 
    restart: always
    container_name: "portfoliodb"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT:-3308}:3306
    command: --log-bin-trust-function-creators=1
    volumes:
      - db_data:/var/lib/mysql
      - ./config/scripts/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./config/scripts/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql
      - ./config/conf.d/db.cnf:/etc/mysql/conf.d/db.cnf:ro

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "--password=${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  # stack pour le container d'api
  app:
    container_name: app-portfolio
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PROJECT_NAME=${PROJECT_NAME}
      - API_VERSION=${API_VERSION}
      - AUTH_TOKEN_ENDPOINT=${AUTH_TOKEN_ENDPOINT}
      - AUTH_TOKEN_VALIDATE_ENDPOINT=${AUTH_TOKEN_VALIDATE_ENDPOINT}
      - DEFAULT_ADMIN_LAST_NAME=${DEFAULT_ADMIN_LAST_NAME}
      - DEFAULT_ADMIN_FIRST_NAME=${DEFAULT_ADMIN_FIRST_NAME}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - KEY_INIT=${KEY_INIT}
      - SERVER_MEDIA=${SERVER_MEDIA}
      - AUTO_SETUP=${AUTO_SETUP}
      - GITHUB_API_URL=${GITHUB_API_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USER=${GITHUB_USER}
      - GITLAB_API_URL=${GITLAB_API_URL}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_USER=${GITLAB_USER}
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - ${PORT_APP:-8079}:8079
    volumes:
      - ./medias:/code/medias
    healthcheck:
      test: curl -f http://localhost:8079/api/v1/healthcheck || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /code/app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/.pytest_cache"
        - action: rebuild
          path: ./backend/requirements.txt

  # container pour l'authentification
  auth:
    container_name: auth-portfolio
    environment:
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - AUTH_PROJECT_NAME=${AUTH_PROJECT_NAME}
      - AUTH_API_VERSION=${AUTH_API_VERSION}
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./auth/app/
          target: /code/app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/.pytest_cache"
        - action: rebuild
          path: ./auth/requirements.txt

  front-portfolio:
    container_name: front-portfolio
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "8073:5173"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./frontend/public/
          target: /app/public
        - action: sync
          path: ./frontend/src/
          target: /app/src/
        - action: rebuild
          path: ./frontend/package.json
  medias:
    container_name: medias
    image: nginx:alpine
    ports:
      - "8071:80"
    volumes:
      - ./medias/:/usr/share/nginx/html/medias
    restart: always

volumes:
  db_data:
