services:
  db:
    image: mariadb:12.0.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_DB_HOST: db
      PORT: $PORT
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      PROJECT_NAME: ${PROJECT_NAME}
      API_VERSION: ${API_VERSION}
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - ${PORT:-8080}:8080
volumes:
  db_data:
