services:
  app:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      PROJECT_NAME: ${PROJECT_NAME}
      API_VERSION: ${API_VERSION}
    build: .
    restart: always
    ports:
      - ${PORT:-8070}:8080
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/.pytest_cache"
        - action: rebuild
          path: ./requirements.txt
