site_name: Portfolio
site_url: https://api.portfolio.in.org/mysite
theme:
  name: material
  palette:
    # Pallette pour le mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Changer pour le theme sombre

    # Pallette pour le mode clair
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Changer pour le theme clair
